# -*- coding: utf-8 -*-
DOMAIN = "pvrouter"
CONF_TOPIC_PREFIX = "topic_prefix"

TOPIC_DATA = "{}/DATA"
TOPIC_SETMODE = "{}/SETMODE"
TOPIC_SWITCH = "{}/SWITCH"
TOPIC_RESET = "{}/RESET"
TOPIC_BOOST = "{}/BOOST"

ATTR_TEMP1 = "TEMP1"
ATTR_TEMP2 = "TEMP2"
ATTR_PIN = "PIN"
ATTR_INJECT = "INJECT"
ATTR_MODE = "MODEINFO"
