DOMAIN = "pvrouter"
CONF_TOPIC_PREFIX = "mqtt_prefix"

# Topics
TOPIC_DATA = "{}/DATA"
TOPIC_SETMODE = "{}/SETMODE"
TOPIC_SWITCH = "{}/SWITCH"
TOPIC_RESET = "{}/RESET"

# Attributs du JSON
ATTR_TEMP1 = "TEMP1"
ATTR_TEMP2 = "TEMP2"
ATTR_PIN = "PIN"
ATTR_INJECT = "INJECT"

ATTR_MODE = "MODEINFO"
