name: Release

on:
  release:
    types: [published]

env:

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZIP integration folder
    
        run: |
          cd custom_components/pvrouter
          zip pvrouter.zip -r ./
          
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_components/pvrouter/pvrouter.zip
          asset_name: pvrouter.zip
          tag: ${{ github.ref }}
          overwrite: true
