name: Validate

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:

  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Linting (Ruff)
        uses: astral-sh/ruff-action@v1

      - name: HACS validation
     
        uses: hacs/action@main
        with:
          category: integration

      - name: HASSFEST
     
        uses: home-assistant/actions/hassfest@master
